### ISSUE TITLE
Individuals and Paretos as JSON

### ISSUE THREAD

**Issue by lapplislazuli** [wubero/Guided-MT-Code2Vec#2]
Currently the results are saved as a .txt and then mined again later in the python scripts. 

I'd like that every individual has a .json or some other file format and be saved like this next to the altered files / in an output folder. 
Later, the python does not work on the .txt but run on the folder and find all .jsons for later use. 

Example JSON one Individual: 

```json
{
    "hash" : "xxxxxxx",
    "first_seen_gen" : 1,
    "last_seen_gen" : 5, 
    "transformers" : [
        {"transformer" : "iftrue","seed":42}, {"transformer" : "lambda","seed":24}
    ],
    "f1":0.8,
    "mrr":0.75,
     ....
}
```

ParetoJSON: 

```json
{
    "Generation" : 10,
    "Metrics" : [ "F1", "Transformers"],
    "individuals" : [
        ... list of above ...
    ]
}
```

This should help easing use later in python, with plotting different things and looking for new / different trends.

**Comment by lapplislazuli** [comment]
Change: 
```
    "first_seen_gen" : 1,
    "last_seen_gen" : 5, 
```

To: 

```
    "introduced_gen": 4
     "age": 3
```

As genes can be "re-introduced" by accident. this should be covered by this.

**Comment by wubero** [comment]
Per individual a json file that illustrates the scores for all metrics & individual stats.

Rewrite the code that each individual gets outputted once it is no longer in the next generation
-> need some logic between generations to check what changes

**Comment by lapplislazuli** [comment]
Closed in favour of [the ciselab repo](https://github.com/ciselab/Guided-MT-Code2Vec/issues/1)
